OpenStreetMap/OpenStreetMap/Models/Address.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace OpenStreetMap.Models
{  /// <summary>
    /// ViewModel pro MVC a Model pro Entity Framework - výpis uložených adres
    /// </summary>
    public class Address
    {
        [Key]
        public Guid Id { get; set; }
        [Display(Name="Zeměpisná šířka")]
        public double Latitude { get; set; }
        [Display(Name = "Zeměpisná délka")]
        public double Longitude { get; set; }
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Display(Name = "Město")]
        public string City { get; set; }
        [Display(Name = "Číslo popisné")]
        public string StreetNumber { get; set; }
        [Display(Name="PSČ")]
        public int PostalCode { get; set; }
         [Display(Name = "Země")]
        public string Country { get; set; }
    }
}

OpenStreetMap/OpenStreetMap/Models/CoordinateViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Device.Location;
using System.ComponentModel.DataAnnotations;
namespace OpenStreetMap.Models
{
    public class CoordinateViewModel
    {
        /// <summary>
        /// ViewModel pro zadávání dat určených k vyhledávání adres
        /// </summary>
        /// 

        [Required(ErrorMessage = "Údaj o zeměpisné šířce je povinný")]
        [Range(-90, 90, ErrorMessage="Neplatný údaj zeměpisné šířky")]
        [Display(Name = "Zeměpisná šířka")]
        public double Latitude { get; set; }
        [Range(-180, 180,ErrorMessage="Neplatný údaj zeměpisné délky")]
        [Required(ErrorMessage = "Údaj o zeměpisné délce je povinný")]
        [Display(Name = "Zeměpisná délka")]
        public double Longitude { get; set; }
        [Required(ErrorMessage = "Údaj o emailové adrese je povinný")]
        [EmailAddress(ErrorMessage="Emailová adresa není platná")]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }
}

OpenStreetMap/OpenStreetMap/Models/NominatimResponseAddress.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OpenStreetMap.Models
{
    public class NominatimResponseAddress
    {   /// <summary>
        /// Model pro deserializaci dat z Nonimatimu
        /// </summary>

        public string road { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string house_number { get; set; }
        public string postcode { get; set; }
        public string country { get; set; }

    }
}

OpenStreetMap/OpenStreetMap/Models/NominatimResponseRoot.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OpenStreetMap.Models
{
    public class NominatimResponseRoot
    {
        /// <summary>
        /// Model pro deserializaci dat z Nonimatimu
        /// </summary>
        public string place_id { get; set; }
        public string licence { get; set; }
        public string osm_type { get; set; }
        public string osm_id { get; set; }
        public string lat { get; set; }
        public string lon { get; set; }
        public string display_name { get; set; }
        public NominatimResponseAddress address { get; set; }
    }
}

OpenStreetMap/OpenStreetMap/Controllers/NominatimController.cs
using OpenStreetMap.Models;
using OpenStreetMap.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace OpenStreetMap.Controllers
{
    public class NominatimController : Controller
    {
        // GET: Nominatim
        public ActionResult Index()
        {
            
            return View();
        }

        public ActionResult ShowHistory()
        {
            try
            {
                DbService DbService = new DbService();
                IEnumerable<Address> history = DbService.GetHistory();
                return View(history);
            }

            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "Chyba při komunikaci s databází");
            }
           
        }
    }
}

OpenStreetMap/OpenStreetMap/Controllers/NominatimReverseController.cs
using OpenStreetMap.Models;
using OpenStreetMap.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace OpenStreetMap.Controllers
{
    public class NominatimReverseController : ApiController
    {
        [HttpPost]
        [Route("Api/Nominatim/Reverse/Query")]
        public HttpResponseMessage Query(CoordinateViewModel coordinates)
        {
            NominatimService nominatimService;
            if(coordinates == null)
                return Request.CreateErrorResponse(HttpStatusCode.BadRequest, "Nebyli odeslány žádná data");
            if (!ModelState.IsValid)
            {
                return Request.CreateErrorResponse(HttpStatusCode.BadRequest, ModelState);
            }
            try
            {
                nominatimService = new NominatimService();
                if (!nominatimService.GetData(coordinates.Latitude, coordinates.Longitude))
                    return Request.CreateErrorResponse(HttpStatusCode.NotFound, "Na daných souřadnicích nebyla nalezena žádná adresa");
            }

            catch
            {
                return Request.CreateResponse(HttpStatusCode.ServiceUnavailable, "Došlo k chybě při komunikaci s externí službou");
            }
                Address address = nominatimService.TransferData();
                address.Latitude = coordinates.Latitude;
                address.Longitude = coordinates.Longitude;
                address.Email = coordinates.Email;
                address.Id = Guid.NewGuid();
                try
                {
                    DbService dbservice = new DbService();
                    dbservice.WriteAddress(address);
                }
                catch
                {
                    return Request.CreateResponse(HttpStatusCode.InternalServerError, "Chyba při ukládání dat do databáze");
                }
                return Request.CreateResponse(HttpStatusCode.OK, "Data vloženy do databáze");
            

            
            
        }
        
    }
}

OpenStreetMap/OpenStreetMap/Views/Nominatim/Index.cshtml
@model OpenStreetMap.Models.CoordinateViewModel

@{
    ViewBag.Title = "Reverzní překlad GPS na adresu";
}

<h2>@ViewBag.Title</h2>



    
    <div class="form-horizontal">
        <h4>Nový dotaz</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">
                Výsledek dotazu
            </span>
            <div class="col-md-10">
               <div id="Result"></div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <Button id="SendQuery" class="btn btn-default" >Odeslat dotaz</Button>
            </div>
        </div>
    </div>


<script src="~/Scripts/jquery-1.10.2.min.js"></script>



<script src="~/Scripts/NominatimAjax.js"></script>

OpenStreetMap/OpenStreetMap/Views/Nominatim/ShowHistory.cshtml
@model IEnumerable<OpenStreetMap.Models.Address>

@{
    ViewBag.Title = "Historie zadaných dat";
}

<h2>@ViewBag.Title</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Latitude)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Longitude)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StreetNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PostalCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th></th>   </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Latitude)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Longitude)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StreetNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostalCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Country)
        </td>
       
    </tr>
}

</table>

OpenStreetMap/OpenStreetMap/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nominatim Gateway", "Index", "Nominatim", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Nový dotaz", "Index")</li>
                    <li>@Html.ActionLink("Zobrazit historii", "ShowHistory")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
       
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>